package com.example.util

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

enum class Language(val code: String, val nativeName: String) {
    AR("ar", "العربية"),
    EN("en", "English")
}

object LocalizationManager {
    private val _currentLanguage = MutableStateFlow(Language.AR)
    val currentLanguage: StateFlow<Language> = _currentLanguage

    var language: Language
        get() = _currentLanguage.value
        set(value) {
            _currentLanguage.value = value
        }

    fun get(key: String, lang: Language = _currentLanguage.value): String {
        return translations[lang]?.get(key) ?: translations[Language.EN]?.get(key) ?: key
    }

    private val translations = mapOf(
        Language.EN to mapOf(
            "app_name" to "Quranic Audio Studio",
            "offline" to "Offline Mode",
            "all_files" to "All Audio Files",
            "categories" to "Categories",
            "quran" to "Noble Quran",
            "music" to "Aesthetic Sound / Nasheed",
            "lectures" to "Lectures",
            "other" to "Islamic Audios & Others",
            "recent" to "Recently Played",
            "favorites" to "My Favorites",
            "playlists" to "My Playlists",
            "now_playing" to "Now Playing",
            "settings" to "Settings & Systems",
            "scan_device" to "Device Multi-Thread Scanner",
            "ignore_warn" to "Ignore Folder Substrings",
            "trigger_scan" to "Trigger Scan",
            "populate" to "Populate Mock",
            "searching" to "Fuzzy Search Engine",
            "about" to "About AI Engine",
            "version" to "Version 1.0.0 (Astrovelet)",
            "welcome" to "Welcome Back",
            "home" to "Home",
            "search" to "Search",
            "library" to "Library",
            "studio" to "Islamic Reels Studio",
            "online" to "Online Quran Network",
            "morning" to "Good Morning",
            "afternoon" to "Good Afternoon",
            "evening" to "Good Evening",
            "quick_desc" to "Beautiful smart audio catalog & manager with modern local DSP.",
            "empty_list" to "Your catalog is empty. Scan device or populate mock list.",
            "qari_bio" to "Qari Biography & Details",
            "verified" to "Verified Reciter",
            "online_reciters" to "Online Reciters Directory",
            "select_reciter" to "Browse Reciters",
            "popular_qaris" to "High-Fidelity Server Streamers",
            "quran_enhancer" to "Smart Quran Sound Enhancer",
            "enhancer_desc" to "Custom-built DSP optimizer for holy recitation vocals.",
            "bass" to "Vocal Bass Depth",
            "reverb" to "Acoustic Ambient Reverb",
            "speed" to "Playback Speed",
            "pitch" to "Vocal Pitch Modifier",
            "sleep" to "Sleep Timer (Minutes)",
            "cancel" to "Cancel",
            "save" to "Save",
            "delete" to "Delete",
            "create_playlist" to "Create Playlist",
            "add_to_playlist" to "Add to Playlist",
            "remove_from_playlist" to "Remove from Playlist",
            "options" to "Audio Options",
            "scan_target" to "Search Target Folder",
            "language" to "Application Interface Language",
            "language_desc" to "Change the system and menus localization fully.",
            "duration" to "Duration",
            "artist" to "Qari / Artist",
            "back" to "Return Back",
            "search_hint" to "Search by Qari, Surah name, or album...",
            "peace_be_upon_you" to "Peace be upon you",
            "quran_shuffle" to "Quran Shuffle",
            "smart_search" to "Smart Search",
            "featured_offline" to "Featured Offline Recitations",
            "sandbox_banner" to "Sandbox Mode: Using simulated high-fidelity Quran database. Works 100% offline with physical playback animations.",
            "empty_recent" to "No recently played files inside database cache.",
            "ai_certified" to "AI Certified Reciter Bio",
            "qari_location" to "Origin & Location",
            "qari_influence" to "Activity & Influence",
            "qari_school" to "Recitation Style & School Highlight",
            "qari_bio_title" to "Professional & Academic Quranic Bio",
            "done_reading" to "Acknowledged & Done",
            "quick_options" to "Quick Track Operations",
            "play_now" to "Play Now",
            "fav" to "Favorite",
            "infav" to "Favorited",
            "path" to "Physical File Path",
            "copy_path" to "Copy Path",
            "copied" to "Path copied to clipboard successfully!",
            "file_size" to "File Size",
            "quality" to "Bitrate & Format",
            "recitation_type" to "Category/Style",
            "assem" to "Hafs A'n Asim",
            "mixed_sound" to "Ambient Sound",
            "bio_not_found" to "Biographic information not mapped under this name.",
            "bio_not_found_desc" to "The registered artist tag is \"%s\". You can update track tags or view bios in Studio.",
            "all_recitations" to "All Recitations",
            "by_qari" to "By Reciter",
            "by_surah" to "By Surah",
            "by_status" to "Completeness",
            "by_quality" to "Sample Quality",
            "complete_surahs" to "Complete Surahs",
            "partial_recitations" to "Partial Ayas & Clips",
            "high_quality" to "High Fidelity (>=128 kbps)",
            "standard_quality" to "Standard Fidelity (<128 kbps)",
            "empty_favorite" to "You have no favorited recitations yet. Click heart icons next to tracks to populate.",
            "create_playlist_desc" to "Input a memorable title and optional description for your new collection.",
            "title_hint" to "Collection Title...",
            "desc_hint" to "Description (Optional)...",
            "qari_online" to "Browse Online Qaris",
            "surah_online" to "Select Surah",
            "stream_online" to "Stream Directly",
            "connecting" to "Buffering from high-speed Quran cloud...",
            "online_empty" to "Check internet connectivity. Streaming is fully responsive.",
            "main_tab" to "Main",
            "quran_tab" to "Quran",
            "studio_tab" to "Studio",
            "library_tab" to "Library",
            "settings_tab" to "Settings",
            "battery_eco" to "Battery Eco-Mode Optimizer",
            "battery_eco_desc" to "Reduces waveform visualization render cycles to sustain battery life.",
            "astro_theme" to "Astrovelet Theme UI Design",
            "astro_theme_desc" to "Luxurious dark theme custom built for OLED displays.",
            "backup_sync" to "Library Storage Backup & Sync",
            "export_xml" to "Export XML",
            "export_success" to "Export complete! XML backup flushed to target path.",
            "import_sync" to "Import / Sync",
            "import_success" to "Database synchronization and merge completed successfully.",
            "reset_db" to "Truncate / Reset Database Core",
            "reset_db_desc" to "Offline index cleared.",
            "about_app_desc" to "A modern offline application that utilizes an embedded high-speed heuristic and fuzzy spelling pattern ML scoring engine to instantly classify physical file folders, detect Quranic recitations, and sort qaris from other music genres without drawing any bandwidth or compromising battery consumption.\n\nBuilt in Jetpack Compose, utilising native low-latency Android audio DSP effects (Equalizer, Bass Boost, Preset Reverb, Speed, and Pitch controllers) coupled with a complete custom smart Quran Enhance sound mode.",
            "about_app_version" to "Version 1.0.0 (Astrovelet Solid Offline Edition)\nNo Cloud telemetry, no telemetry logging, 100% private.",
            "all_tracks" to "View All Tracks",
            "only_local" to "Local Files Only",
            "only_online" to "Cloud Streams Only",
            "online_quran_tab" to "Online Network",
            "online_header" to "Online Recitations Directory",
            "online_subtitle" to "Stream verse-by-verse and complete surahs directly from public Quran servers",
            "lyrics_tab" to "Quran Verses",
            "enable_lyrics" to "Enable Verses Display",
            "disable_lyrics" to "Disable Verses",
            "lyrics_loading" to "Fetching Noble Quran verses from cloud...",
            "lyrics_disabled" to "Verses display has been disabled. Toggle the switch to display the words of the Quran."
        ),
        Language.AR to mapOf(
            "app_name" to "استوديو الصوتيات القرآني",
            "offline" to "وضع عدم الاتصال بالشبكة",
            "all_files" to "كل الملفات الصوتية",
            "categories" to "التصنيفات المتاحة",
            "quran" to "القرآن الكريم",
            "music" to "الأناشيد والصوتيات العذبة",
            "lectures" to "المحاضرات الإسلامية",
            "other" to "صوتيات وملفات أخرى",
            "recent" to "المشغلة حديثاً",
            "favorites" to "المفضلة الخاصة بي",
            "playlists" to "قوائم التشغيل الخاصة بي",
            "now_playing" to "مشغل الآن",
            "settings" to "إعدادات ومعلمات النظام",
            "scan_device" to "فاحص مساحة التخزين الذكي",
            "ignore_warn" to "تجاهل مسارات وملفات النظام",
            "trigger_scan" to "إطلاق فحص المسارات",
            "populate" to "توليد مكتبة افتراضية",
            "searching" to "محرك البحث الذكي والفوري",
            "about" to "حول معمارية محرك الذكاء الاصطناعي",
            "version" to "الإصدار 1.0.0 (النسخة المستقلة)",
            "welcome" to "مرحباً بك مجدداً",
            "home" to "الرئيسية",
            "search" to "البحث",
            "library" to "المكتبة",
            "studio" to "استوديو صناعة المقاطع",
            "online" to "القرآن المباشر (أونلاين)",
            "morning" to "صباح الخير والبركة",
            "afternoon" to "طاب يومك بكل خير",
            "evening" to "مساء الخير والأنوار",
            "quick_desc" to "منصة ذكية متكاملة لإدارة الصوتيات وتحسينها بمؤثرات صوتية فريدة.",
            "empty_list" to "المكتبة فارغة حالياً. يرجى فحص الذاكرة أو توليد المكتبة الافتراضية.",
            "qari_bio" to "السيرة الذاتية وتفاصيل القارئ",
            "verified" to "قارئ معتمد وموثق",
            "online_reciters" to "دليل القراء والبث المباشر",
            "select_reciter" to "استعراض قائمة القراء",
            "popular_qaris" to "بث عالي الدقة من خوادم البث المباشرة",
            "quran_enhancer" to "محسن الصوت القرآني الذكي",
            "enhancer_desc" to "معالج ترددات خاص تم ضبطه يدوياً لإبراز جمال التلاوة وعمق المقامات.",
            "bass" to "عمق وضخامة الصوت الرخيم",
            "reverb" to "مؤثر الصدى والمساحة الصوتية",
            "speed" to "سرعة تشغيل الصوتيات",
            "pitch" to "طبقة ونبرة الصوت",
            "sleep" to "مؤقت النوم التلقائي (بالدقائق)",
            "cancel" to "إلغاء الأمر",
            "save" to "حفظ البيانات",
            "delete" to "حذف",
            "create_playlist" to "إنشاء قائمة تشغيل جديدة",
            "add_to_playlist" to "إضافة إلى قائمة تشغيل",
            "remove_from_playlist" to "إزالة من قائمة التشغيل",
            "options" to "خيارات ومعلومات الملف",
            "scan_target" to "مجلد المسح الرئيسي المستهدف",
            "language" to "لغة واجهة التطبيق كاملة",
            "language_desc" to "تبديل لغة القوائم والتقارير والنظام بالكامل بكل سهولة.",
            "duration" to "المدة الزمنية للفيديو",
            "artist" to "القارئ / المنشد / المحاضر",
            "back" to "الرجوع للخلف",
            "search_hint" to "ابحث باسم الشيخ، اسم السورة أو الألبوم...",
            "peace_be_upon_you" to "تحية السلام والوقار",
            "quran_shuffle" to "تشغيل عشوائي للقرآن",
            "smart_search" to "البحث الذكي الفوري",
            "featured_offline" to "تلاوات ممتازة من الذاكرة",
            "sandbox_banner" to "وضع المحاكاة: نستخدم تلاوات عالية الدقة جاهزة للتشغيل والاستماع وتطبيق الخصائص الفورية والمؤثرات.",
            "empty_recent" to "لم يتم تشغيل أي ملف مؤخراً لحفظه بالكاش المؤقت.",
            "ai_certified" to "سيرة موثقة ومدققة بالذكاء الاصطناعي",
            "qari_location" to "المقر والبلد والمنشأ",
            "qari_influence" to "فترة النشاط والتأثير القرآني",
            "qari_school" to "منهج المدرسة وأسلوب التلاوة والمقامات",
            "qari_bio_title" to "السيرة الذاتية المهنية والأكاديمية والقرآنية",
            "done_reading" to "تمت قراءة وفهم السيرة العطرة",
            "quick_options" to "خيارات سريعة وتفصيلية",
            "play_now" to "تشغيل الآن فوراً",
            "fav" to "إضافة للمفضلة",
            "infav" to "موجود بالمفضلة",
            "path" to "مسار الملف الفعلي على الجهاز",
            "copy_path" to "نسخ المسار الكامل",
            "copied" to "تم نسخ مسار الملف للحافظة بنجاح!",
            "file_size" to "حجم الملف الصوتي",
            "quality" to "معدل الترميز والدقة",
            "recitation_type" to "نوع التلاوة والرواية",
            "assem" to "ترتيل حفص عن عاصم المتقن",
            "mixed_sound" to "صوت مدمج ومحسن للخشوع",
            "bio_not_found" to "المعلومات البيوغرافية للاسم غير متوفرة بعد",
            "bio_not_found_desc" to "الاسم المسجل في وسم الصوت هو \"%s\"، يمكنك تعديل بطاقة الصوت أو إضافة سيرة من الأستوديو.",
            "all_recitations" to "جميع التلاوات الصوتية",
            "by_qari" to "تصنيف حسب المشايخ والقراء",
            "by_surah" to "تصنيف حسب الرواية والسور",
            "by_status" to "اكتمال ومطابقة السور",
            "by_quality" to "مستوى دقة الصوت والترددات",
            "complete_surahs" to "السور الكاملة والمسجلة بالكامل",
            "partial_recitations" to "المقاطع والمقاطع والآيات المجزأة",
            "high_quality" to "دقة وجودة عالية في الصوتيات (>= 128 كيلوبت)",
            "standard_quality" to "دقة عادية ومساحة منخفضة (< 128 كيلوبت)",
            "empty_favorite" to "لم تقم بتفضيل أي ملف بعد. اضغط على أيقونة القلب على التراكات لإدراجها هنا.",
            "create_playlist_desc" to "أقحم اسماً فريداً ووصفاً اختيارياً لإنشاء تشكيلة مخصصة للصوتيات المفضلة.",
            "title_hint" to "عنوان التشكيلة الجديدة...",
            "desc_hint" to "أضف وصفاً للتشكيلة (اختياري)...",
            "qari_online" to "اختر قارئاً أونلاين وبث حي",
            "surah_online" to "اختر السورة المطلوبة للاستماع",
            "stream_online" to "بدء البث الصوتي المباشر",
            "connecting" to "جاري الاتصال والتحميل من الخوادم السحابية للقرآن...",
            "online_empty" to "يرجى التحقق من اتصالك بالشبكة والإنترنت لبدء الاستماع مباشرة.",
            "main_tab" to "الرئيسية",
            "quran_tab" to "القرآن",
            "studio_tab" to "الأستوديو",
            "library_tab" to "المكتبة",
            "settings_tab" to "الإعدادات",
            "battery_eco" to "محسن استهلاك البطارية والنظام",
            "battery_eco_desc" to "يقلل من دورات رندر الأمواج الصوتية لتوفير طاقة البطارية لفترات أطول.",
            "astro_theme" to "واجهة مستخدم ذات سمة مظلمة فاخرة",
            "astro_theme_desc" to "تصميم فاخر وعميق بالكامل مخصص ومثالي لشاشات الـ OLED.",
            "backup_sync" to "النسخ الاحتياطي والمزامنة السحابية",
            "export_xml" to "تصدير كملف XML",
            "export_success" to "تم التصدير بنجاح! تم حفظ البيانات في المسار المكتوب.",
            "import_sync" to "استيراد ومزامنة",
            "import_success" to "تم استيراد التفضيلات والبيانات ومزامنة الكاش بنجاح التام.",
            "reset_db" to "حذف وتفريغ الكاش وتهيئة قاعدة البيانات",
            "reset_db_desc" to "تم تفريغ كافة ملفات التخزين المؤقت وحذف البيانات الفورية.",
            "about_app_desc" to "برنامج متكامل يعتمد على فاحص ذكي محلي سريع لتشخيص مسارات المجلدات وفرز التلاوات والخطب والأناشيد دون أي جهد أو استهلاك للانترنت.\n\nتطبيق مصمم بنظام Compose ولغة Kotlin ويضم لوحة دمج وتحسين صوتيات فريدة وتأثيرات الصدى والبيس ومجسم الصوت القرآني لإنتاج بيئة استماع ممتازة.",
            "about_app_version" to "النسخة 1.0.0 (النسخة الفاخرة والآمنة للاستخدام المحلي المستقل).\nلا يتم جمع أي بيانات، خصوصيتك 100% محفوظة ومؤمنة.",
            "all_tracks" to "مشاهدة كل الصوتيات المتاحة",
            "only_local" to "الملفات الصوتية المحلية فقط",
            "only_online" to "ملفات البث المباشر السحابية فقط",
            "online_quran_tab" to "البث السحابي",
            "online_header" to "دليل شيوخ وقراء بث التلاوة المباشر",
            "online_subtitle" to "استمع وافحص سور القرآن الكريم بأصوات عمالقة القراء مباشرة عبر الإنترنت من خوادم شبكة القرآن وسيرفراتها.",
            "lyrics_tab" to "الكلمات والآيات",
            "enable_lyrics" to "تفعيل عرض الآيات",
            "disable_lyrics" to "إلغاء تفعيل عرض الكلمات",
            "lyrics_loading" to "جاري جلب آيات السورة الكريمة من الخوادم...",
            "lyrics_disabled" to "تم إلغاء تفعيل عرض الكلمات والآيات. قم بتفعيل الزر المخصص لمشاهدة كلمات القرآن الكريم أثناء الاستماع."
        )
    )
}
