package com.example.util

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

enum class Language(val code: String, val nativeName: String) {
    AR("ar", "العربية"),
    EN("en", "English")
}

object LocalizationManager {
    private val _currentLanguage = MutableStateFlow(Language.AR)
    val currentLanguage: StateFlow<Language> = _currentLanguage

    var language: Language
        get() = _currentLanguage.value
        set(value) {
            _currentLanguage.value = value
        }

    fun get(key: String, lang: Language = _currentLanguage.value): String {
        return translations[lang]?.get(key) ?: translations[Language.EN]?.get(key) ?: key
    }

    private val translations = mapOf(
        Language.EN to mapOf(
            "app_name" to "Quranic Audio Studio",
            "offline" to "Offline Mode",
            "all_files" to "All Audio Files",
            "categories" to "Categories",
            "quran" to "Noble Quran",
            "music" to "Aesthetic Sound / Nasheed",
            "lectures" to "Lectures",
            "other" to "Islamic Audios & Others",
            "recent" to "Recently Played",
            "favorites" to "My Favorites",
            "playlists" to "My Playlists",
            "now_playing" to "Now Playing",
            "settings" to "Settings & Systems",
            "scan_device" to "Device Multi-Thread Scanner",
            "ignore_warn" to "Ignore Folder Substrings",
            "trigger_scan" to "Trigger Scan",
            "populate" to "Populate Mock",
            "searching" to "Fuzzy Search Engine",
            "about" to "About AI Engine",
            "version" to "Version 1.0.0 (Astrovelet)",
            "welcome" to "Welcome Back",
            "home" to "Home",
            "search" to "Search",
            "library" to "Library",
            "studio" to "Islamic Reels Studio",
            "online" to "Online Quran Network",
            "morning" to "Good Morning",
            "afternoon" to "Good Afternoon",
            "evening" to "Good Evening",
            "quick_desc" to "Beautiful smart audio catalog & manager with modern local DSP.",
            "empty_list" to "Your catalog is empty. Scan device or populate mock list.",
            "qari_bio" to "Qari Biography & Details",
            "verified" to "Verified Reciter",
            "online_reciters" to "Online Reciters Directory",
            "select_reciter" to "Browse Reciters",
            "popular_qaris" to "High-Fidelity Server Streamers",
            "quran_enhancer" to "Smart Quran Sound Enhancer",
            "enhancer_desc" to "Custom-built DSP optimizer for holy recitation vocals.",
            "bass" to "Vocal Bass Depth",
            "reverb" to "Acoustic Ambient Reverb",
            "speed" to "Playback Speed",
            "pitch" to "Vocal Pitch Modifier",
            "sleep" to "Sleep Timer (Minutes)",
            "cancel" to "Cancel",
            "save" to "Save",
            "delete" to "Delete",
            "create_playlist" to "Create Playlist",
            "add_to_playlist" to "Add to Playlist",
            "remove_from_playlist" to "Remove from Playlist",
            "options" to "Audio Options",
            "scan_target" to "Search Target Folder",
            "language" to "Application Interface Language",
            "language_desc" to "Change the system and menus localization fully.",
            "duration" to "Duration",
            "artist" to "Qari / Artist",
            "back" to "Return Back",
            "search_hint" to "Search by Qari, Surah name, or album...",
            "peace_be_upon_you" to "Peace be upon you",
            "quran_shuffle" to "Quran Shuffle",
            "smart_search" to "Smart Search",
            "featured_offline" to "Featured Offline Recitations",
            "sandbox_banner" to "Sandbox Mode: Using simulated high-fidelity Quran database. Works 100% offline with physical playback animations.",
            "empty_recent" to "No recently played files inside database cache.",
            "ai_certified" to "AI Certified Reciter Bio",
            "qari_location" to "Origin & Location",
            "qari_influence" to "Activity & Influence",
            "qari_school" to "Recitation Style & School Highlight",
            "qari_bio_title" to "Professional & Academic Quranic Bio",
            "done_reading" to "Acknowledged & Done",
            "quick_options" to "Quick Track Operations",
            "play_now" to "Play Now",
            "fav" to "Favorite",
            "infav" to "Favorited",
            "path" to "Physical File Path",
            "copy_path" to "Copy Path",
            "copied" to "Path copied to clipboard successfully!",
            "file_size" to "File Size",
            "quality" to "Bitrate & Format",
            "recitation_type" to "Category/Style",
            "assem" to "Hafs A'n Asim",
            "mixed_sound" to "Ambient Sound",
            "bio_not_found" to "Biographic information not mapped under this name.",
            "bio_not_found_desc" to "The registered artist tag is \"%s\". You can update track tags or view bios in Studio.",
            "all_recitations" to "All Recitations",
            "by_qari" to "By Reciter",
            "by_surah" to "By Surah",
            "by_status" to "Completeness",
            "by_quality" to "Sample Quality",
            "complete_surahs" to "Complete Surahs",
            "partial_recitations" to "Partial Ayas & Clips",
            "high_quality" to "High Fidelity (>=128 kbps)",
            "standard_quality" to "Standard Fidelity (<128 kbps)",
            "empty_favorite" to "You have no favorited recitations yet. Click heart icons next to tracks to populate.",
            "create_playlist_desc" to "Input a memorable title and optional description for your new collection.",
            "title_hint" to "Collection Title...",
            "desc_hint" to "Description (Optional)...",
            "qari_online" to "Browse Online Qaris",
            "surah_online" to "Select Surah",
            "stream_online" to "Stream Directly",
            "connecting" to "Buffering from high-speed Quran cloud...",
            "online_empty" to "Check internet connectivity. Streaming is fully responsive.",
            "main_tab" to "Main",
            "quran_tab" to "Quran",
            "studio_tab" to "Studio",
            "library_tab" to "Library",
            "settings_tab" to "Settings",
            "battery_eco" to "Battery Eco-Mode Optimizer",
            "battery_eco_desc" to "Reduces waveform visualization render cycles to sustain battery life.",
            "astro_theme" to "Astrovelet Theme UI Design",
            "astro_theme_desc" to "Luxurious dark theme custom built for OLED displays.",
            "backup_sync" to "Library Storage Backup & Sync",
            "export_xml" to "Export XML",
            "export_success" to "Export complete! XML backup flushed to target path.",
            "import_sync" to "Import / Sync",
            "import_success" to "Database synchronization and merge completed successfully.",
            "reset_db" to "Truncate / Reset Database Core",
            "reset_db_desc" to "Offline index cleared.",
            "about_app_desc" to "A modern offline application that utilizes an embedded high-speed heuristic and fuzzy spelling pattern ML scoring engine to instantly classify physical file folders, detect Quranic recitations, and sort qaris from other music genres without drawing any bandwidth or compromising battery consumption.\n\nBuilt in Jetpack Compose, utilising native low-latency Android audio DSP effects (Equalizer, Bass Boost, Preset Reverb, Speed, and Pitch controllers) coupled with a complete custom smart Quran Enhance sound mode.",
            "about_app_version" to "Version 1.0.0 (Astrovelet Solid Offline Edition)\nNo Cloud telemetry, no telemetry logging, 100% private.",
            "all_tracks" to "View All Tracks",
            "only_local" to "Local Files Only",
            "only_online" to "Cloud Streams Only",
            "online_quran_tab" to "Online Network",
            "online_header" to "Online Recitations Directory",
            "online_subtitle" to "Stream verse-by-verse and complete surahs directly from public Quran servers",
            "lyrics_tab" to "Quran Verses",
            "enable_lyrics" to "Enable Verses Display",
            "disable_lyrics" to "Disable Verses",
            "lyrics_loading" to "Fetching Noble Quran verses from cloud...",
            "lyrics_disabled" to "Verses display has been disabled. Toggle the switch to display the words of the Quran.",

            // New additions for QuranSectionView.kt
            "tab_reciters" to "Reciters",
            "tab_surahs" to "Surahs",
            "tab_structure" to "Structure",
            "tab_quality_desc" to "Audio Quality",
            "no_reciters" to "No reciters detected yet. Please scan or generate.",
            "offline_files_count" to "%d recitation files offline",
            "back_reciters" to "Back to Reciters",
            "no_surahs_yet" to "No identified Surahs yet.",
            "no_complete_surahs" to "No complete surahs.",
            "no_clips" to "No clips detected.",
            "high_fidelity_title" to "High Fidelity (256-320 kbps)",
            "std_fidelity_title" to "Standard Fidelity (< 256 kbps)",

            // New additions for LibrarySectionView.kt
            "library_management" to "Library Management",
            "library_subtitle" to "Classified audio indexes stored in local DB",
            "favorites_sub" to "%s Saved Tracks",
            "playlists_sub" to "%s Custom Playlists",
            "non_quran_divider" to "Separated Non-Quran Files",
            "music_sub" to "%s Songs Detected",
            "lectures_sub" to "%s Files Classified",
            "other_sub" to "%s Voice Memos / Static",
            "favorites_title" to "Favorites",
            "playlists_title" to "Custom Playlists",
            "music_section" to "Chants & Music Section",
            "lectures_section" to "Islamic Lectures & Talks",
            "other_section" to "Other Audio Files",
            "back_library" to "Back to Library Dashboard",
            "no_favorites" to "No favorites added yet.",
            "no_music" to "No music tracks detected.",
            "no_lectures" to "No lectures classified yet.",
            "no_other_files" to "No other audio files detected.",
            "playlist_empty" to "This playlist is empty. Add tracks from the audio options menu.",
            "track_removed" to "Track removed successfully.",

            // New additions for AudioStudioView.kt
            "audio_studio" to "Audio Studio",
            "studio_subtitle" to "Offline digital audio DSP processing",
            "select_modify_file" to "Select Audio File to Modify:",
            "no_local_files" to "No local files available. Match demo files first.",
            "select_modify_action" to "Select Modification Action:",
            "trim_audio" to "Trim Audio",
            "trim_desc" to "Crop / Slice portions",
            "amplify_vol" to "Amplify Volume",
            "amplify_desc" to "Gain multiplier boost",
            "concatenate_files" to "Concatenate Files",
            "concatenate_desc" to "Merge two tracks",
            "spectral_denoise" to "Spectral Denoise",
            "spectral_desc" to "Dampen static noise",
            "extract_video" to "Extract Audio from Video",
            "extract_video_desc" to "Simulate ripping MP3/AAC from camera or MP4 downloads",
            "exit_studio" to "Exit Studio Workspace",
            "crop_range" to "Crop / Trim Audio Range",
            "target_lbl" to "Target: %s",
            "selected_seg_dur" to "Selected segment duration: %d seconds",
            "trim_start" to "Trim Start Offset: %ds",
            "trim_end" to "Trim End Limit: %ds",
            "execute_crop" to "Execute Crop",
            "boost_amp" to "Boost Audio Signal Amplitude",
            "selected_factor" to "Selected factor multiplier: %.1fx",
            "softer_lbl" to "0.5x (Softer)",
            "safe_lbl" to "1.5x (Safe)",
            "loud_lbl" to "3.0x (Loud/Warning)",
            "apply_gain" to "Apply Gain Boost",
            "merge_files" to "Merge Two Audio Files together",
            "segment_a" to "Segment A: %s",
            "select_segment_b" to "Select Segment B to link:",
            "execute_merge" to "Execute Merge",
            "apply_spectral" to "Apply Spectral Noise Filter",
            "dampen_noise" to "Dampen Noise",
            "isolate_video" to "Isolate Audio from Local Video",
            "sim_video_extract" to "Simulated video track extraction offline",
            "video_path_lbl" to "Video file path / label",
            "extract_mp3" to "Extract MP3 Stream",
            "log_console" to "DSP Logging Console",
            "please_select_first" to "Please select an audio file first",

            // New additions for SearchSectionView.kt
            "search_desc" to "Fuzzy matching with phonetic Arabic support",
            "search_tip" to "Try typing: 'دوسري' (finds Yasser), 'باسط' (finds Abdul Basit), 'رحيم' (finds Ar-Rahman / Ar-Raheem) are supported.",
            "match_results" to "%d Matching Results Found",
            "no_matches" to "No local matches found. Try other keywords.",
            "suggested_folders" to "Suggested Search Folders",
            "cat_quran" to "Quran Recitations",
            "cat_sermons" to "Sermons & Talks",
            "cat_chants" to "Chants",
            "cat_music" to "Music Recalls"
        ),
        Language.AR to mapOf(
            "app_name" to "استوديو الصوتيات القرآني",
            "offline" to "وضع عدم الاتصال بالشبكة",
            "all_files" to "كل الملفات الصوتية",
            "categories" to "التصنيفات المتاحة",
            "quran" to "القرآن الكريم",
            "music" to "الأناشيد والصوتيات العذبة",
            "lectures" to "المحاضرات الإسلامية",
            "other" to "صوتيات وملفات أخرى",
            "recent" to "المشغلة حديثاً",
            "favorites" to "المفضلة الخاصة بي",
            "playlists" to "قوائم التشغيل الخاصة بي",
            "now_playing" to "مشغل الآن",
            "settings" to "إعدادات ومعلمات النظام",
            "scan_device" to "فاحص مساحة التخزين الذكي",
            "ignore_warn" to "تجاهل مسارات وملفات النظام",
            "trigger_scan" to "إطلاق فحص المسارات",
            "populate" to "توليد مكتبة افتراضية",
            "searching" to "محرك البحث الذكي والفوري",
            "about" to "حول معمارية محرك الذكاء الاصطناعي",
            "version" to "الإصدار 1.0.0 (النسخة المستقلة)",
            "welcome" to "مرحباً بك مجدداً",
            "home" to "الرئيسية",
            "search" to "البحث",
            "library" to "المكتبة",
            "studio" to "استوديو صناعة المقاطع",
            "online" to "القرآن المباشر (أونلاين)",
            "morning" to "صباح الخير والبركة",
            "afternoon" to "طاب يومك بكل خير",
            "evening" to "مساء الخير والأنوار",
            "quick_desc" to "منصة ذكية متكاملة لإدارة الصوتيات وتحسينها بمؤثرات صوتية فريدة.",
            "empty_list" to "المكتبة فارغة حالياً. يرجى فحص الذاكرة أو توليد المكتبة الافتراضية.",
            "qari_bio" to "السيرة الذاتية وتفاصيل القارئ",
            "verified" to "قارئ معتمد وموثق",
            "online_reciters" to "دليل القراء والبث المباشر",
            "select_reciter" to "استعراض قائمة القراء",
            "popular_qaris" to "بث عالي الدقة من خوادم البث المباشرة",
            "quran_enhancer" to "محسن الصوت القرآني الذكي",
            "enhancer_desc" to "معالج ترددات خاص تم ضبطه يدوياً لإبراز جمال التلاوة وعمق المقامات.",
            "bass" to "عمق وضخامة الصوت الرخيم",
            "reverb" to "مؤثر الصدى والمساحة الصوتية",
            "speed" to "سرعة تشغيل الصوتيات",
            "pitch" to "طبقة ونبرة الصوت",
            "sleep" to "مؤقت النوم التلقائي (بالدقائق)",
            "cancel" to "إلغاء الأمر",
            "save" to "حفظ البيانات",
            "delete" to "حذف",
            "create_playlist" to "إنشاء قائمة تشغيل جديدة",
            "add_to_playlist" to "إضافة إلى قائمة تشغيل",
            "remove_from_playlist" to "إزالة من قائمة التشغيل",
            "options" to "خيارات ومعلومات الملف",
            "scan_target" to "مجلد المسح الرئيسي المستهدف",
            "language" to "لغة واجهة التطبيق كاملة",
            "language_desc" to "تبديل لغة القوائم والتقارير والنظام بالكامل بكل سهولة.",
            "duration" to "المدة الزمنية للفيديو",
            "artist" to "القارئ / المنشد / المحاضر",
            "back" to "الرجوع للخلف",
            "search_hint" to "ابحث باسم الشيخ، اسم السورة أو الألبوم...",
            "peace_be_upon_you" to "تحية السلام والوقار",
            "quran_shuffle" to "تشغيل عشوائي للقرآن",
            "smart_search" to "البحث الذكي الفوري",
            "featured_offline" to "تلاوات ممتازة من الذاكرة",
            "sandbox_banner" to "وضع المحاكاة: نستخدم تلاوات عالية الدقة جاهزة للتشغيل والاستماع وتطبيق الخصائص الفورية والمؤثرات.",
            "empty_recent" to "لم يتم تشغيل أي ملف مؤخراً لحفظه بالكاش المؤقت.",
            "ai_certified" to "سيرة موثقة ومدققة بالذكاء الاصطناعي",
            "qari_location" to "المقر والبلد والمنشأ",
            "qari_influence" to "فترة النشاط والتأثير القرآني",
            "qari_school" to "منهج المدرسة وأسلوب التلاوة والمقامات",
            "qari_bio_title" to "السيرة الذاتية المهنية والأكاديمية والقرآنية",
            "done_reading" to "تمت قراءة وفهم السيرة العطرة",
            "quick_options" to "خيارات سريعة وتفصيلية",
            "play_now" to "تشغيل الآن فوراً",
            "fav" to "إضافة للمفضلة",
            "infav" to "موجود بالمفضلة",
            "path" to "مسار الملف الفعلي على الجهاز",
            "copy_path" to "نسخ المسار الكامل",
            "copied" to "تم نسخ مسار الملف للحافظة بنجاح!",
            "file_size" to "حجم الملف الصوتي",
            "quality" to "معدل الترميز والدقة",
            "recitation_type" to "نوع التلاوة والرواية",
            "assem" to "ترتيل حفص عن عاصم المتقن",
            "mixed_sound" to "صوت مدمج ومحسن للخشوع",
            "bio_not_found" to "المعلومات البيوغرافية للاسم غير متوفرة بعد",
            "bio_not_found_desc" to "الاسم المسجل في وسم الصوت هو \"%s\"، يمكنك تعديل بطاقة الصوت أو إضافة سيرة من الأستوديو.",
            "all_recitations" to "جميع التلاوات الصوتية",
            "by_qari" to "تصنيف حسب المشايخ والقراء",
            "by_surah" to "تصنيف حسب الرواية والسور",
            "by_status" to "اكتمال ومطابقة السور",
            "by_quality" to "مستوى دقة الصوت والترددات",
            "complete_surahs" to "السور الكاملة والمسجلة بالكامل",
            "partial_recitations" to "المقاطع والمقاطع والآيات المجزأة",
            "high_quality" to "دقة وجودة عالية في الصوتيات (>= 128 كيلوبت)",
            "standard_quality" to "دقة عادية ومساحة منخفضة (< 128 كيلوبت)",
            "empty_favorite" to "لم تقم بتفضيل أي ملف بعد. اضغط على أيقونة القلب على التراكات لإدراجها هنا.",
            "create_playlist_desc" to "أقحم اسماً فريداً ووصفاً اختيارياً لإنشاء تشكيلة مخصصة للصوتيات المفضلة.",
            "title_hint" to "عنوان التشكيلة الجديدة...",
            "desc_hint" to "أضف وصفاً للتشكيلة (اختياري)...",
            "qari_online" to "اختر قارئاً أونلاين وبث حي",
            "surah_online" to "اختر السورة المطلوبة للاستماع",
            "stream_online" to "بدء البث الصوتي المباشر",
            "connecting" to "جاري الاتصال والتحميل من الخوادم السحابية للقرآن...",
            "online_empty" to "يرجى التحقق من اتصالك بالشبكة والإنترنت لبدء الاستماع مباشرة.",
            "main_tab" to "الرئيسية",
            "quran_tab" to "القرآن",
            "studio_tab" to "الأستوديو",
            "library_tab" to "المكتبة",
            "settings_tab" to "الإعدادات",
            "battery_eco" to "محسن استهلاك البطارية والنظام",
            "battery_eco_desc" to "يقلل من دورات رندر الأمواج الصوتية لتوفير طاقة البطارية لفترات أطول.",
            "astro_theme" to "واجهة مستخدم ذات سمة مظلمة فاخرة",
            "astro_theme_desc" to "تصميم فاخر وعميق بالكامل مخصص ومثالي لشاشات الـ OLED.",
            "backup_sync" to "النسخ الاحتياطي والمزامنة السحابية",
            "export_xml" to "تصدير كملف XML",
            "export_success" to "تم التصدير بنجاح! تم حفظ البيانات في المسار المكتوب.",
            "import_sync" to "استيراد ومزامنة",
            "import_success" to "تم استيراد التفضيلات والبيانات ومزامنة الكاش بنجاح التام.",
            "reset_db" to "حذف وتفريغ الكاش وتهيئة قاعدة البيانات",
            "reset_db_desc" to "تم تفريغ كافة ملفات التخزين المؤقت وحذف البيانات الفورية.",
            "about_app_desc" to "برنامج متكامل يعتمد على فاحص ذكي محلي سريع لتشخيص مسارات المجلدات وفرز التلاوات والخطب والأناشيد دون أي جهد أو استهلاك للانترنت.\n\nتطبيق مصمم بنظام Compose ولغة Kotlin ويضم لوحة دمج وتحسين صوتيات فريدة وتأثيرات الصدى والبيس ومجسم الصوت القرآني لإنتاج بيئة استماع ممتازة.",
            "about_app_version" to "النسخة 1.0.0 (النسخة الفاخرة والآمنة للاستخدام المحلي المستقل).\nلا يتم جمع أي بيانات، خصوصيتك 100% محفوظة ومؤمنة.",
            "all_tracks" to "مشاهدة كل الصوتيات المتاحة",
            "only_local" to "الملفات الصوتية المحلية فقط",
            "only_online" to "ملفات البث المباشر السحابية فقط",
            "online_quran_tab" to "البث السحابي",
            "online_header" to "دليل شيوخ وقراء بث التلاوة المباشر",
            "online_subtitle" to "استمع وافحص سور القرآن الكريم بأصوات عمالقة القراء مباشرة عبر الإنترنت من خوادم شبكة القرآن وسيرفراتها.",
            "lyrics_tab" to "الكلمات والآيات",
            "enable_lyrics" to "تفعيل عرض الآيات",
            "disable_lyrics" to "إلغاء تفعيل عرض الكلمات",
            "lyrics_loading" to "جاري جلب آيات السورة الكريمة من الخوادم...",
            "lyrics_disabled" to "تم إلغاء تفعيل عرض الكلمات والآيات. قم بتفعيل الزر المخصص لمشاهدة كلمات القرآن الكريم أثناء الاستماع.",

            // New additions for QuranSectionView.kt
            "tab_reciters" to "القراء",
            "tab_surahs" to "السور",
            "tab_structure" to "البنية والاكتمال",
            "tab_quality_desc" to "جودة الصوت",
            "no_reciters" to "لم يتم العثور على قراء حالياً. يرجى المسح أو توليد مكتبة افتراضية.",
            "offline_files_count" to "%d ملف تلاوة متاح بدون إنترنت",
            "back_reciters" to "الرجوع للقراء",
            "no_surahs_yet" to "لا توجد سور معروفة ومصنفة بعد.",
            "no_complete_surahs" to "لا توجد سور كاملة.",
            "no_clips" to "لم يتم العثور على مقاطع تلاوة.",
            "high_fidelity_title" to "دقة وجودة عالية (256-320 كيلوبت في الثانية)",
            "std_fidelity_title" to "دقة عادية ومساحة منخفضة (< 256 كيلوبت في الثانية)",

            // New additions for LibrarySectionView.kt
            "library_management" to "إدارة المكتبة والصوتيات",
            "library_subtitle" to "الفهارس الصوتية المصنفة والمحفوظة محلياً",
            "favorites_sub" to "%s تراك محفوظ في المفضلة",
            "playlists_sub" to "%s قوائم تشغيل مخصصة",
            "non_quran_divider" to "الملفات غير المصنفة كقرآن",
            "music_sub" to "%s ملفات صوتية وأناشيد تم رصدها",
            "lectures_sub" to "%s دروس ومحاضرات مصنفة",
            "other_sub" to "%s مذكرات وملفات صوتية أخرى",
            "favorites_title" to "المفضلة والمحفوظات",
            "playlists_title" to "قوائم التشغيل المخصصة",
            "music_section" to "قسم الأناشيد والصوتيات",
            "lectures_section" to "الخطب والمحاضرات الإسلامية",
            "other_section" to "الملفات الصوتية والمذكرات",
            "back_library" to "الرجوع إلى لوحة تحكم المكتبة",
            "no_favorites" to "لا توجد تلاوات مفضلة مضافة حالياً.",
            "no_music" to "لم يتم العثور على أناشيد أو صوتيات عذبة.",
            "no_lectures" to "لم يتم العثور على خطب ومحاضرات مصنفة حالياً.",
            "no_other_files" to "لا توجد ملفات صوتية أخرى مضافة.",
            "playlist_empty" to "قائمة التشغيل هذه فارغة حالياً. أضف تراك صوتي إليها من خيارات التراك.",
            "track_removed" to "تمت إزالة التراك من قائمة التشغيل بنجاح.",

            // New additions for AudioStudioView.kt
            "audio_studio" to "استوديو الصوتيات",
            "studio_subtitle" to "معالجة وتحرير الصوت الرقمي غير المباشر (أوفلاين)",
            "select_modify_file" to "اختر الملف الصوتي المطلوب تعديله:",
            "no_local_files" to "لا توجد ملفات محلية متاحة بعد. يرجى توليد أو جلب ملفات ديمو أولاً.",
            "select_modify_action" to "اختر إجراء التعديل المطلوب:",
            "trim_audio" to "قص وتقطيع الصوت",
            "trim_desc" to "اقتصاص جزء من الملف وحفظه",
            "amplify_vol" to "تضخيم ورفع الصوت",
            "amplify_desc" to "زيادة جين وتضخيم الإشارة الصوتية",
            "concatenate_files" to "دمج وربط الملفات",
            "concatenate_desc" to "دمج ملفين صوتيين معاً متتاليين",
            "spectral_denoise" to "تنقية وتصفية الضجيج",
            "spectral_desc" to "كتم صوت التشويش والهواء الخلفي للخشوع",
            "extract_video" to "استخراج الصوت من الفيديو",
            "extract_video_desc" to "محاكاة تحويل فيديو MP4 لكاميرا أو تنزيلات إلى صوت MP3/AAC",
            "exit_studio" to "الخروج من مساحة عمل الاستوديو",
            "crop_range" to "قص وتحديد مجال الملف الصوتي",
            "target_lbl" to "الملف المستهدف: %s",
            "selected_seg_dur" to "مدة المقطع المختار: %d ثانية",
            "trim_start" to "بداية الاقتصاص المائل: %d ثانية",
            "trim_end" to "نهاية الاقتصاص المائل: %d ثانية",
            "execute_crop" to "بدء واقتصاص الصوت الآن",
            "boost_amp" to "رفع وتضخيم الإشارة الصوتية الحالية",
            "selected_factor" to "مضاعف التضخيم المختار: %.1f ضعف",
            "softer_lbl" to "0.5 ضعف (تخفيض الصوت)",
            "safe_lbl" to "1.5 ضعف (تضخيم آمن)",
            "loud_lbl" to "3.0 ضعف (تضخيم عالي / تحذير)",
            "apply_gain" to "تطبيق وتثبيت رفع الصوت",
            "merge_files" to "دمج وخلط ملفين صوتيين معاً",
            "segment_a" to "الملف (أ): %s",
            "select_segment_b" to "اختر الملف الثاني (ب) للدمج والتوصيل:",
            "execute_merge" to "تطبيق دمج المسارات",
            "apply_spectral" to "تطبيق مرشح التصفية والترددات للضوضاء",
            "dampen_noise" to "تطبيق خافض التشويش",
            "isolate_video" to "عزل الصوت تماماً من الفيديو المحلي",
            "sim_video_extract" to "محاكاة استخراج ترميز الصوت أوفلاين وسريع",
            "video_path_lbl" to "اسم أو مسار ملف الفيديو المستهدف",
            "extract_mp3" to "بدء الاستخراج الرقمي MP3",
            "log_console" to "لوحة تتبع عمليات المعالجة الرقمية DSP",
            "please_select_first" to "يرجى تحديد ملف صوتي من القائمة أولاً لتلقي المعالجة",

            // New additions for SearchSectionView.kt
            "search_desc" to "البحث باستخدام محرك الترابط الصوتي المطابق للعربية الفصحى",
            "search_tip" to "جرب كتابة: 'دوسري' (ياسر الدوسري)، 'باسط' (عبد الباسط)، 'رحيم' (سورة الرحمن)...",
            "match_results" to "تم العثور على %d نتائج مطابقة",
            "no_matches" to "لم يتم العثور على أي تلاوة مطابقة. حاول البحث بكلمة أخرى.",
            "suggested_folders" to "مجلدات وتوصيات المسح المقترحة",
            "cat_quran" to "تلاوات وقراءات القرآن الكريم",
            "cat_sermons" to "الخطب والمواعظ والدروس",
            "cat_chants" to "الابتهالات والأناشيد العذبة",
            "cat_music" to "صوتيات وملفات مدمجة أخرى"
        )
    )
}
